[build]
  # Directorio donde se ejecuta el build
  base = "."
  
  # Comando para hacer el build
  command = "npm run build"
  
  # Directorio donde se genera el build (debe coincidir con vite.config.js)
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Configuración para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
